package demo.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @return the value of PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @param price the value for PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}