package demo.mybatis.dao;

import demo.mybatis.model.Store;
import java.util.List;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    Store selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    List<Store> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Sun May 07 20:21:13 EEST 2023
     */
    int updateByPrimaryKey(Store record);
}